### ISSUE TITLE
MyModel.reindex causing index [INDEX_NAME/UUID] already exists with elasticsearch 8.x only (not 7.x)

### ISSUE THREAD

**Issue by PikachuEXE** [ankane/searchkick#1641]
I switched to searchkick recently (great gem btw) since `elasticsearch-model` stuck in 7.x for long time
Now I want to upgrade ElasticSearch from 7.x to 8.x
Found issue when reindexing models: 
```
Elasticsearch::Transport::Transport::Errors::BadRequest:
[400] {
  "error":  {
    "root_cause":[{"type":"resource_already_exists_exception","reason":"index [INDEX_NAME/UUID] already exists","index_uuid":"INDEX_UUID","index":"INDEX_NAME"}],
    "type":"resource_already_exists_exception",
    "reason":"index [INDEX_NAME/UUID] already exists",
    "index_uuid":"INDEX_UUID",
    "index":"INDEX_NAME"
  },
  "status":400
}
```

<details>
<summary>Exception backtrace</summary>

```
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elastic-transport-8.2.2/lib/elastic/transport/transport/base.rb:228:in `__raise_transport_error'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elastic-transport-8.2.2/lib/elastic/transport/transport/base.rb:346:in `perform_request'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elastic-transport-8.2.2/lib/elastic/transport/transport/http/faraday.rb:36:in `perform_request'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elastic-transport-8.2.2/lib/elastic/transport/client.rb:174:in `perform_request'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elasticsearch-8.8.0/lib/elasticsearch.rb:71:in `method_missing'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elasticsearch-api-8.8.0/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elasticsearch-api-8.8.0/lib/elasticsearch/api/actions/indices/create.rb:51:in `create'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/searchkick-5.3.0/lib/searchkick/index.rb:16:in `create'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/searchkick-5.3.0/lib/searchkick/index.rb:261:in `create_index'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/searchkick-5.3.0/lib/searchkick/index.rb:365:in `full_reindex'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/searchkick-5.3.0/lib/searchkick/index.rb:254:in `reindex'
/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/searchkick-5.3.0/lib/searchkick/model.rb:77:in `searchkick_reindex'

```

</details>

## To reproduce (ES8) (See working ES7 version below)

`es8.rb` (Run with `ruby es8.rb`
```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  # gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  gem "searchkick", ">= 5.3.0"
  # uncomment one
  gem "elasticsearch", ">= 8.8.0", "< 9"
  # gem "opensearch-ruby"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Server version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick
end

Product.reindex(mode: :inline)
Product.create!(name: "Test")
Product.search_index.refresh
p Product.search("test", fields: [:name]).response

```

`docker-compose.es8.yml` (start with `docker compose -f docker-compose.es8.yml up`, reset data with `docker compose -f docker-compose.es8.yml down -v`)
```yaml
---
version: "3.8"

# See all software versions @ https://www.docker.elastic.co

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
```

## Env
- Ruby: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [arm64-darwin21]`

## Working (ES7)

`es7.rb` (Run with `ruby es7.rb`
```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  # gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  gem "searchkick", ">= 5.3.0"
  # uncomment one
  gem "elasticsearch", ">= 7.17.7", "< 8"
  # gem "opensearch-ruby"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Server version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick
end

Product.reindex(mode: :inline)
Product.create!(name: "Test")
Product.search_index.refresh
p Product.search("test", fields: [:name]).response

```

`docker-compose.es7.yml` (start with `docker compose -f docker-compose.es7.yml up`, reset data with `docker compose -f docker-compose.es7.yml down -v`)
```yaml
---
version: "3.8"

# See all software versions @ https://www.docker.elastic.co

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.11
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

```

## Additional context
Maybe similar issue: https://github.com/ankane/searchkick/issues/1474
Also I use `Product.reindex(mode: :inline)` (I already running it in background jobs normally)

## More debugging 1
Index creation works with `Elasticsearch::Client` not `Searchkick.client`
```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  # gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  gem "searchkick", ">= 5.3.0"
  # uncomment one
  gem "elasticsearch", ">= 8.8.0", "< 9"
  # gem "opensearch-ruby"
end

es_client = Elasticsearch::Client.new
puts(es_client.inspect)
es_client.indices.delete(index: 'my_es_index') if es_client.indices.exists index: 'my_es_index'
es_client.indices.create(index: 'my_es_index')
puts("manual my_es_index client.indices.create done")

sk_client = Searchkick.client
puts(sk_client.inspect)
sk_client.indices.delete(index: 'my_sk_index') if sk_client.indices.exists index: 'my_sk_index'
sk_client.indices.create(index: 'my_sk_index')
puts("manual my_sk_index client.indices.create done")
```

<details>
<summary>`es_client.inspect`</summary>

```
#<Elasticsearch::Client:0x000000010847c0d0 @verified=false, @opaque_id_prefix=nil, @transport=#<Elastic::Transport::Client:0x0000000108493fc8 @arguments={:logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :delay_on_retry=>0, :reload_on_failure=>false, :randomize_hosts=>false, :transport_options=>{:headers=>{"x-elastic-client-meta"=>"es=8.8.0,rb=3.2.2,t=8.2.2,fd=2.7.10,nh=0.3.2"}}, :http=>{:user=>nil, :password=>nil}, :enable_meta_header=>true, :adapter=>:net_http, :retry_on_status=>[]}, @hosts=[{:host=>"localhost", :port=>9200, :protocol=>"http"}], @send_get_body_as="GET", @ca_fingerprint=nil, @transport_class=Elastic::Transport::Transport::HTTP::Faraday, @transport=#<Elastic::Transport::Transport::HTTP::Faraday:0x0000000108476ab8 @state_mutex=#<Thread::Mutex:0x0000000108476a18>, @hosts=[{:host=>"localhost", :port=>9200, :protocol=>"http"}], @options={:logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :delay_on_retry=>0, :reload_on_failure=>false, :randomize_hosts=>false, :transport_options=>{:headers=>{"x-elastic-client-meta"=>"es=8.8.0,rb=3.2.2,t=8.2.2,fd=2.7.10,nh=0.3.2"}}, :http=>{:user=>nil, :password=>nil}, :enable_meta_header=>true, :adapter=>:net_http, :retry_on_status=>[]}, @block=#<Proc:0x00000001084769a0 /Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elastic-transport-8.2.2/lib/elastic/transport/client.rb:158>, @compression=false, @user_agent="elastic-transport-ruby/8.2.2 (RUBY_VERSION: 3.2.2; darwin arm64; Faraday v2.7.10)", @connections=#<Elastic::Transport::Transport::Connections::Collection:0x000000010845dd38 @connections=[#<Elastic::Transport::Transport::Connections::Connection:0x0000000108493348 @host={:host=>"localhost", :port=>9200, :protocol=>"http"}, @connection=#<Faraday::Connection:0x0000000108493c58 @parallel_manager=nil, @headers={"x-elastic-client-meta"=>"es=8.8.0,rb=3.2.2,t=8.2.2,fd=2.7.10,nh=0.3.2", "User-Agent"=>"elastic-transport-ruby/8.2.2 (RUBY_VERSION: 3.2.2; darwin arm64; Faraday v2.7.10)", "Content-Type"=>"application/json"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @manual_proxy=false, @builder=#<Faraday::RackBuilder:0x0000000108474380 @adapter=Faraday::Adapter::NetHttp, @handlers=[]>, @url_prefix=#<URI::HTTP http://localhost:9200/>, @proxy=nil>, @options={:resurrect_timeout=>60}, @verified=false, @state_mutex=#<Thread::Mutex:0x000000010845de28>, @dead=false, @failures=0>], @selector=#<Elastic::Transport::Transport::Connections::Selector::RoundRobin:0x000000010845db80 @connections=#<Elastic::Transport::Transport::Connections::Collection:0x000000010845dd38 ...>, @mutex=#<Thread::Mutex:0x000000010845d950>, @current=nil>>, @serializer=#<Elastic::Transport::Transport::Serializer::MultiJson:0x000000010845d8d8 @transport=#<Elastic::Transport::Transport::HTTP::Faraday:0x0000000108476ab8 ...>>, @protocol="http", @logger=nil, @tracer=nil, @sniffer=#<Elastic::Transport::Transport::Sniffer:0x000000010845d7c0 @transport=#<Elastic::Transport::Transport::HTTP::Faraday:0x0000000108476ab8 ...>, @timeout=1>, @counter=0, @counter_mtx=#<Thread::Mutex:0x000000010845d6f8>, @last_request_at=2023-07-24 13:53:20.462164 +0800, @reload_connections=false, @reload_after=10000, @resurrect_after=60, @retry_on_status=[]>>>
```

</details>

<details>
<summary>`sk_client.inspect`</summary>

```
#<Elasticsearch::Client:0x0000000108417540 @verified=false, @opaque_id_prefix=nil, @transport=#<Elastic::Transport::Client:0x00000001084174f0 @arguments={:url=>nil, :transport_options=>{:request=>{:timeout=>10}, :headers=>{:content_type=>"application/json", "x-elastic-client-meta"=>"es=8.8.0,rb=3.2.2,t=8.2.2,fd=2.7.10,nh=0.3.2"}}, :retry_on_failure=>2, :logger=>nil, :tracer=>nil, :reload_connections=>false, :delay_on_retry=>0, :reload_on_failure=>false, :randomize_hosts=>false, :http=>{:user=>nil, :password=>nil}, :enable_meta_header=>true, :adapter=>:net_http, :retry_on_status=>[]}, @hosts=[{:host=>"localhost", :port=>9200, :protocol=>"http"}], @send_get_body_as="GET", @ca_fingerprint=nil, @transport_class=Elastic::Transport::Transport::HTTP::Faraday, @transport=#<Elastic::Transport::Transport::HTTP::Faraday:0x0000000108b31920 @state_mutex=#<Thread::Mutex:0x00000001086e3cd8>, @hosts=[{:host=>"localhost", :port=>9200, :protocol=>"http"}], @options={:url=>nil, :transport_options=>{:request=>{:timeout=>10}, :headers=>{:content_type=>"application/json", "x-elastic-client-meta"=>"es=8.8.0,rb=3.2.2,t=8.2.2,fd=2.7.10,nh=0.3.2"}}, :retry_on_failure=>2, :logger=>nil, :tracer=>nil, :reload_connections=>false, :delay_on_retry=>0, :reload_on_failure=>false, :randomize_hosts=>false, :http=>{:user=>nil, :password=>nil}, :enable_meta_header=>true, :adapter=>:net_http, :retry_on_status=>[]}, @block=#<Proc:0x00000001086e3be8 /Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/elastic-transport-8.2.2/lib/elastic/transport/client.rb:158>, @compression=false, @user_agent="elastic-transport-ruby/8.2.2 (RUBY_VERSION: 3.2.2; darwin arm64; Faraday v2.7.10)", @connections=#<Elastic::Transport::Transport::Connections::Collection:0x00000001082ff360 @connections=[#<Elastic::Transport::Transport::Connections::Connection:0x00000001084163c0 @host={:host=>"localhost", :port=>9200, :protocol=>"http"}, @connection=#<Faraday::Connection:0x000000010843a8d8 @parallel_manager=nil, @headers={"Content-Type"=>"application/json", "x-elastic-client-meta"=>"es=8.8.0,rb=3.2.2,t=8.2.2,fd=2.7.10,nh=0.3.2", "User-Agent"=>"elastic-transport-ruby/8.2.2 (RUBY_VERSION: 3.2.2; darwin arm64; Faraday v2.7.10)"}, @params={}, @options=#<Faraday::RequestOptions timeout=10>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @manual_proxy=false, @builder=#<Faraday::RackBuilder:0x00000001086e3238 @adapter=Faraday::Adapter::NetHttp, @handlers=[Searchkick::Middleware]>, @url_prefix=#<URI::HTTP http://localhost:9200/>, @proxy=nil>, @options={:resurrect_timeout=>60}, @verified=false, @state_mutex=#<Thread::Mutex:0x00000001082ff428>, @dead=false, @failures=0>], @selector=#<Elastic::Transport::Transport::Connections::Selector::RoundRobin:0x00000001082ff2e8 @connections=#<Elastic::Transport::Transport::Connections::Collection:0x00000001082ff360 ...>, @mutex=#<Thread::Mutex:0x00000001082ff2c0>, @current=nil>>, @serializer=#<Elastic::Transport::Transport::Serializer::MultiJson:0x00000001082ff298 @transport=#<Elastic::Transport::Transport::HTTP::Faraday:0x0000000108b31920 ...>>, @protocol="http", @logger=nil, @tracer=nil, @sniffer=#<Elastic::Transport::Transport::Sniffer:0x00000001082ff270 @transport=#<Elastic::Transport::Transport::HTTP::Faraday:0x0000000108b31920 ...>, @timeout=1>, @counter=0, @counter_mtx=#<Thread::Mutex:0x00000001082ff248>, @last_request_at=2023-07-24 13:53:50.566569 +0800, @reload_connections=false, @reload_after=10000, @resurrect_after=60, @retry_on_status=[]>>>
```

</details>

**Comment by PikachuEXE** [comment]
Turns out ES client auto retry creating index on timeout (default 10s)

And the slow index creation seems to be caused by not having this config in `docker-compose.es8.yml`:
(But `docker-compose.es7.yml` works fine without this config)
```yaml
environment:
  # `cluster.routing.allocation.disk.threshold_enabled=false` needed or annoying error happens very easily
  # https://stackoverflow.com/questions/63880017/elasticsearch-docker-flood-stage-disk-watermark-95-exceeded
  - cluster.routing.allocation.disk.threshold_enabled=false
```
So if I update `docker-compose.es8.yml` to the following I don't even need to update timeout via `Searchkick.timeout`

<details>
<summary>`docker-compose.es8.yml`</summary>

```yaml
---
version: "3.8"

# See all software versions @ https://www.docker.elastic.co

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      # `cluster.routing.allocation.disk.threshold_enabled=false` needed or annoying error happens very easily
      # https://stackoverflow.com/questions/63880017/elasticsearch-docker-flood-stage-disk-watermark-95-exceeded
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
```

</details>
